---
# Quick validation playbook - tests openclaw installation on existing server
# Usage: ansible-playbook validate-openclaw.yml -i "IP_ADDRESS," --private-key=hetzner_key

- name: Validate OpenClaw Installation
  hosts: all
  remote_user: root
  gather_facts: false

  vars:
    roboclaw_user: roboclaw
    roboclaw_home: /home/roboclaw

  tasks:
    - name: Check if roboclaw user exists
      ansible.builtin.command: id {{ roboclaw_user }}
      register: user_check
      changed_when: false
      failed_when: false

    - name: Display user check result
      ansible.builtin.debug:
        msg: "{{ 'User exists' if user_check.rc == 0 else 'User does not exist' }}"

    - name: Check pnpm global configuration
      ansible.builtin.shell: |
        pnpm config get global-bin-dir
        pnpm config get global-dir
      become: true
      become_user: "{{ roboclaw_user }}"
      register: pnpm_config
      changed_when: false
      when: user_check.rc == 0

    - name: Display pnpm config
      ansible.builtin.debug:
        msg: "{{ pnpm_config.stdout_lines }}"
      when: user_check.rc == 0

    - name: List globally installed pnpm packages
      ansible.builtin.shell: |
        export PATH="{{ roboclaw_home }}/.local/bin:$PATH"
        pnpm list -g
      become: true
      become_user: "{{ roboclaw_user }}"
      register: pnpm_list
      changed_when: false
      when: user_check.rc == 0

    - name: Display installed packages
      ansible.builtin.debug:
        msg: "{{ pnpm_list.stdout_lines }}"
      when: user_check.rc == 0

    - name: Check if openclaw binary exists
      ansible.builtin.shell: |
        export PATH="{{ roboclaw_home }}/.local/bin:$PATH"
        which openclaw || echo "NOT FOUND"
      become: true
      become_user: "{{ roboclaw_user }}"
      register: which_openclaw
      changed_when: false
      when: user_check.rc == 0

    - name: Display openclaw location
      ansible.builtin.debug:
        msg: "{{ which_openclaw.stdout }}"
      when: user_check.rc == 0

    - name: Verify openclaw installation
      ansible.builtin.shell: |
        export PATH="{{ roboclaw_home }}/.local/bin:$PATH"
        openclaw --version
      become: true
      become_user: "{{ roboclaw_user }}"
      register: openclaw_version
      changed_when: false
      when: user_check.rc == 0

    - name: Display openclaw version
      ansible.builtin.debug:
        msg: "✅ OpenClaw installed: {{ openclaw_version.stdout }}"
      when: user_check.rc == 0 and openclaw_version.rc == 0

    - name: Display failure if openclaw not working
      ansible.builtin.debug:
        msg: "❌ OpenClaw command failed"
      when: user_check.rc == 0 and openclaw_version.rc != 0
