---
- name: Create Hetzner Cloud instance in Finland (Helsinki)
  hosts: localhost
  gather_facts: false

  vars:
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
    server_name: "{{ lookup('env', 'SERVER_NAME') | default('finland-instance', true) }}"
    server_type: "{{ lookup('env', 'SERVER_TYPE') | default('cax11', true) }}"  # 2 vCPU, 4GB RAM, 40GB disk (~€3.29/month, ARM)
    location: "{{ lookup('env', 'LOCATION') | default('hel1', true) }}"     # Helsinki, Finland
    image: "{{ lookup('env', 'IMAGE') | default('ubuntu-24.04', true) }}"
    ssh_key_name: "{{ server_name }}-key"
    ssh_public_key: "{{ lookup('env', 'SSH_PUBLIC_KEY') | default('', true) }}"
    ssh_private_key_path: "{{ lookup('env', 'SSH_PRIVATE_KEY_PATH') | default('./hetzner_key', true) }}"

  tasks:
    - name: Debug provisioning parameters
      ansible.builtin.debug:
        msg: |
          🔍 Provisioning with:
          Server Name: {{ server_name }}
          Server Type: {{ server_type }}
          Location: {{ location }}
          Image: {{ image }}

    - name: Fail if HCLOUD_TOKEN is not set
      ansible.builtin.fail:
        msg: "Please set HCLOUD_TOKEN environment variable with your Hetzner API token"
      when: hcloud_token == ""

    - name: Fail if SSH_PUBLIC_KEY is not set
      ansible.builtin.fail:
        msg: "Please set SSH_PUBLIC_KEY environment variable with your public key"
      when: ssh_public_key == ""

    - name: Create or update SSH key in Hetzner
      hetzner.hcloud.ssh_key:
        api_token: "{{ hcloud_token }}"
        name: "{{ ssh_key_name }}"
        public_key: "{{ ssh_public_key }}"
        state: present
      register: ssh_key

    - name: Delete existing server if it exists (to force fresh deployment with new SSH key)
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        name: "{{ server_name }}"
        state: absent
      ignore_errors: true

    - name: Create Hetzner Cloud server in Helsinki
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        name: "{{ server_name }}"
        server_type: "{{ server_type }}"
        image: "{{ image }}"
        location: "{{ location }}"
        ssh_keys:
          - "{{ ssh_key_name }}"
        state: present
      register: server

    - name: Display server information
      ansible.builtin.debug:
        msg: |
          ✅ Server created successfully!

          Name: {{ server.hcloud_server.name }}
          IPv4: {{ server.hcloud_server.ipv4_address }}
          Type: {{ server.hcloud_server.server_type }}
          Location: {{ server.hcloud_server.location }} (Finland)

    - name: Save server IP to file
      ansible.builtin.copy:
        content: "{{ server.hcloud_server.ipv4_address }}"
        dest: "./finland-instance-ip.txt"
        mode: '0644'

    - name: Add server to in-memory inventory
      ansible.builtin.add_host:
        name: "{{ server.hcloud_server.ipv4_address }}"
        groups: finland_vps
        ansible_user: root
        ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        # Store variables for later use in second play
        deployment_ssh_key_path: "{{ ssh_private_key_path }}"
        deployment_server_name: "{{ server.hcloud_server.name }}"
        deployment_server_type: "{{ server.hcloud_server.server_type }}"
        deployment_server_location: "{{ server.hcloud_server.location }}"
        deployment_server_image: "{{ server.hcloud_server.image }}"

    - name: Wait for SSH to become available
      ansible.builtin.wait_for:
        host: "{{ server.hcloud_server.ipv4_address }}"
        port: 22
        delay: 5
        timeout: 300
        state: started

- name: Fast Install RoboClaw (Essentials Only)
  hosts: finland_vps
  gather_facts: true
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    roboclaw_user: roboclaw
    roboclaw_home: "/home/{{ roboclaw_user }}"
    roboclaw_config_dir: "{{ roboclaw_home }}/.roboclaw"
    nodejs_version: "22.x"

  tasks:
    - name: Display fast install mode
      ansible.builtin.debug:
        msg: |
          ⚡ FAST INSTALL MODE ⚡

          Installing essentials only:
          ✅ Docker CE
          ✅ Node.js 22 + pnpm
          ✅ UFW Firewall
          ✅ RoboClaw
          ✅ Gemini CLI
          ✅ ttyd (browser terminal)

          Skipping (for speed):
          ⏭️  Homebrew
          ⏭️  oh-my-zsh
          ⏭️  46 extra system tools
          ⏭️  Git aliases
          ⏭️  dist-upgrade

          Expected time: ~2-3 minutes (vs ~10-15 minutes)

    - name: Update apt cache only (skip dist-upgrade)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install minimal essential packages
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - git
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    # Create roboclaw user
    - name: Create roboclaw system user
      ansible.builtin.user:
        name: "{{ roboclaw_user }}"
        comment: "RoboClaw system user"
        shell: /bin/bash
        create_home: true
        home: "{{ roboclaw_home }}"

    - name: Add roboclaw user to sudoers with NOPASSWD
      ansible.builtin.copy:
        content: "{{ roboclaw_user }} ALL=(ALL) NOPASSWD:ALL\n"
        dest: "/etc/sudoers.d/{{ roboclaw_user }}"
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Enable lingering for roboclaw user
      ansible.builtin.command: loginctl enable-linger {{ roboclaw_user }}
      changed_when: false

    # Install Docker CE (fast - no extra config)
    - name: Add Docker GPG key
      ansible.builtin.shell:
        cmd: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.shell:
        cmd: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Add roboclaw user to docker group
      ansible.builtin.user:
        name: "{{ roboclaw_user }}"
        groups: docker
        append: true

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    # Configure UFW firewall (fast - minimal rules)
    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Set UFW default policies
      community.general.ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Allow SSH on port 22
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    # Install Node.js 22 (fast)
    - name: Add NodeSource GPG key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
        creates: /usr/share/keyrings/nodesource.gpg

    - name: Add NodeSource repository
      ansible.builtin.shell:
        cmd: |
          echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true

    - name: Install pnpm globally
      ansible.builtin.shell:
        cmd: npm install -g pnpm
        creates: /usr/bin/pnpm

    - name: Install ttyd for browser-based terminal
      ansible.builtin.apt:
        name: ttyd
        state: present

    # Install RoboClaw (fast - from npm, minimal config)
    - name: Create RoboClaw directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ roboclaw_user }}"
        group: "{{ roboclaw_user }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ roboclaw_config_dir }}", mode: '0755' }
        - { path: "{{ roboclaw_config_dir }}/sessions", mode: '0755' }
        - { path: "{{ roboclaw_config_dir }}/credentials", mode: '0700' }
        - { path: "{{ roboclaw_config_dir }}/data", mode: '0755' }
        - { path: "{{ roboclaw_config_dir }}/logs", mode: '0755' }
        - { path: "{{ roboclaw_home }}/.local/share/pnpm", mode: '0755' }
        - { path: "{{ roboclaw_home }}/.local/bin", mode: '0755' }

    - name: Configure pnpm for roboclaw user
      ansible.builtin.shell:
        cmd: |
          pnpm config set global-dir {{ roboclaw_home }}/.local/share/pnpm
          pnpm config set global-bin-dir {{ roboclaw_home }}/.local/bin
        executable: /bin/bash
      become: true
      become_user: "{{ roboclaw_user }}"
      changed_when: true

    - name: Install OpenClaw globally from npm
      ansible.builtin.shell:
        cmd: pnpm install -g openclaw@latest
        executable: /bin/bash
      become: true
      become_user: "{{ roboclaw_user }}"
      environment:
        HOME: "{{ roboclaw_home }}"
        PNPM_HOME: "{{ roboclaw_home }}/.local/share/pnpm"
        PATH: "{{ roboclaw_home }}/.local/bin:{{ ansible_env.PATH }}"
      register: roboclaw_install

    - name: Configure minimal .bashrc for roboclaw user
      ansible.builtin.blockinfile:
        path: "{{ roboclaw_home }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - RoboClaw"
        block: |
          # pnpm configuration
          export PNPM_HOME="{{ roboclaw_home }}/.local/share/pnpm"
          export PATH="{{ roboclaw_home }}/.local/bin:$PNPM_HOME:$PATH"
        create: true
        owner: "{{ roboclaw_user }}"
        group: "{{ roboclaw_user }}"
        mode: '0644'

    - name: Configure .profile for roboclaw user (for non-interactive login shells)
      ansible.builtin.blockinfile:
        path: "{{ roboclaw_home }}/.profile"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - RoboClaw"
        block: |
          # pnpm configuration
          export PNPM_HOME="{{ roboclaw_home }}/.local/share/pnpm"
          export PATH="{{ roboclaw_home }}/.local/bin:$PNPM_HOME:$PATH"
        create: false
        owner: "{{ roboclaw_user }}"
        group: "{{ roboclaw_user }}"
        mode: '0644'

    - name: Install Gemini CLI globally
      ansible.builtin.shell:
        cmd: pnpm install -g @google/gemini-cli
        executable: /bin/bash
      become: true
      become_user: "{{ roboclaw_user }}"
      environment:
        HOME: "{{ roboclaw_home }}"
        PNPM_HOME: "{{ roboclaw_home }}/.local/share/pnpm"
        PATH: "{{ roboclaw_home }}/.local/bin:{{ ansible_env.PATH }}"
      register: gemini_install

    - name: Extract Gemini CLI OAuth credentials from pnpm installation
      ansible.builtin.shell: |
        OAUTH_FILE=$(find {{ roboclaw_home }}/.local/share/pnpm -path '*gemini-cli-core*/oauth2.js' 2>/dev/null | head -1)
        if [ -f "$OAUTH_FILE" ]; then
          CLIENT_ID=$(grep -oP "OAUTH_CLIENT_ID = '\K[^']+" "$OAUTH_FILE" || echo "")
          CLIENT_SECRET=$(grep -oP "OAUTH_CLIENT_SECRET = '\K[^']+" "$OAUTH_FILE" || echo "")
          if [ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ]; then
            echo "CLIENT_ID=$CLIENT_ID"
            echo "CLIENT_SECRET=$CLIENT_SECRET"
          fi
        fi
      register: gemini_oauth_creds
      changed_when: false
      failed_when: false

    - name: Add Gemini OAuth credentials to .profile
      ansible.builtin.blockinfile:
        path: "{{ roboclaw_home }}/.profile"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Gemini OAuth"
        block: |
          # Gemini CLI OAuth credentials (extracted from pnpm installation)
          export GEMINI_CLI_OAUTH_CLIENT_ID='{{ gemini_oauth_creds.stdout_lines[0].split('=')[1] }}'
          export GEMINI_CLI_OAUTH_CLIENT_SECRET='{{ gemini_oauth_creds.stdout_lines[1].split('=')[1] }}'
        create: false
        owner: "{{ roboclaw_user }}"
        group: "{{ roboclaw_user }}"
        mode: '0644'
      when: gemini_oauth_creds.stdout_lines | length >= 2

    - name: Verify roboclaw installation
      ansible.builtin.shell: |
        export PATH="{{ roboclaw_home }}/.local/bin:$PATH"
        openclaw --version
      become: true
      become_user: "{{ roboclaw_user }}"
      register: roboclaw_version
      changed_when: false

    - name: Verify gemini installation
      ansible.builtin.shell: |
        export PATH="{{ roboclaw_home }}/.local/bin:$PATH"
        gemini --version
      become: true
      become_user: "{{ roboclaw_user }}"
      register: gemini_version
      changed_when: false
      failed_when: false

    - name: Display installation complete
      ansible.builtin.debug:
        msg: |
          ⚡ FAST INSTALL COMPLETE! ⚡

          Version: {{ roboclaw_version.stdout }}
          Server: {{ ansible_default_ipv4.address }}
          Install time: ~2-3 minutes (vs ~10-15 with full install)

          ✅ Installed:
          • Docker CE
          • Node.js {{ nodejs_version }}
          • pnpm (latest)
          • UFW Firewall
          • RoboClaw {{ roboclaw_version.stdout }}
          • Gemini CLI {{ gemini_version.stdout | default('installed', true) }}
          • ttyd (browser terminal)

          ⏭️  Skipped for speed:
          • Homebrew (not needed on Linux)
          • oh-my-zsh (use bash instead)
          • 46 extra packages (debugging tools, etc.)
          • Git aliases
          • System dist-upgrade

          Next steps:
          Complete onboarding from the dashboard at http://localhost:3000/instances

          To install extras later:
          apt install zsh tmux htop vim jq

    - name: Create instances directory on local machine
      ansible.builtin.file:
        path: "./instances"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: false

    - name: Get Docker version
      ansible.builtin.command: docker --version
      register: docker_version_output
      changed_when: false

    - name: Get Node.js version
      ansible.builtin.command: node --version
      register: nodejs_version_output
      changed_when: false

    - name: Get pnpm version
      ansible.builtin.command: pnpm --version
      register: pnpm_version_output
      changed_when: false

    - name: Create instance artifact
      ansible.builtin.copy:
        content: |
          # Instance provisioned on {{ ansible_date_time.iso8601 }}
          instances:
            - name: {{ deployment_server_name }}
              ip: {{ ansible_default_ipv4.address }}
              server_type: {{ deployment_server_type }}
              location: {{ deployment_server_location }}
              image: {{ deployment_server_image }}
              provisioned_at: {{ ansible_date_time.iso8601 }}
              install_mode: fast
              onboarding_completed: false
              software:
                os: {{ ansible_distribution }} {{ ansible_distribution_version }}
                kernel: {{ ansible_kernel }}
                docker: {{ docker_version_output.stdout }}
                nodejs: {{ nodejs_version_output.stdout }}
                pnpm: {{ pnpm_version_output.stdout }}
                roboclaw: {{ roboclaw_version.stdout }}
                gemini: {{ gemini_version.stdout | default('installed', true) }}
                ttyd: installed
              configuration:
                roboclaw_user: {{ roboclaw_user }}
                roboclaw_home: {{ roboclaw_home }}
                roboclaw_config_dir: {{ roboclaw_config_dir }}
              firewall:
                ufw_enabled: true
                allowed_ports:
                  - port: 22
                    proto: tcp
                    description: SSH
              ssh:
                key_file: "{{ deployment_ssh_key_path }}"
                public_key_file: "{{ deployment_ssh_key_path }}.pub"
        dest: "../instances/{{ deployment_server_name }}.yml"
        mode: '0644'
      delegate_to: localhost
      become: false

    - name: Display artifact saved message
      ansible.builtin.debug:
        msg: |
          📝 Instance artifact saved to: instances/{{ deployment_server_name }}.yml
