---
# Manage the openclaw systemd service on a remote instance
# Usage: ansible-playbook openclaw-service.yml -i "IP," --private-key=KEY -e "openclaw_state=started"

- name: Manage OpenClaw service
  hosts: all
  remote_user: root
  gather_facts: false

  vars:
    openclaw_state: started        # 'started' or 'stopped'
    openclaw_enabled: true         # whether to enable/disable at boot
    openclaw_service_name: openclaw-gateway  # actual systemd service name
    instance_name: ""              # instance name (passed from run-hetzner.sh)

  tasks:
    - name: Get roboclaw user UID
      ansible.builtin.command: id -u roboclaw
      register: roboclaw_uid
      changed_when: false

    - name: Check if openclaw service unit exists
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ openclaw_service_name }}.service
      register: openclaw_unit_file

    - name: Check if user systemd directory exists
      ansible.builtin.stat:
        path: /home/roboclaw/.config/systemd/user
      register: user_systemd_dir
      when: not openclaw_unit_file.stat.exists

    - name: Check user-level systemd unit
      ansible.builtin.stat:
        path: /home/roboclaw/.config/systemd/user/{{ openclaw_service_name }}.service
      register: openclaw_user_unit_file
      become: true
      become_user: roboclaw
      when: >
        not openclaw_unit_file.stat.exists and
        user_systemd_dir is defined and
        user_systemd_dir.stat is defined and
        user_systemd_dir.stat.exists

    - name: Fail gracefully if service unit not found
      ansible.builtin.fail:
        msg: >
          The openclaw systemd service unit was not found at
          /etc/systemd/system/{{ openclaw_service_name }}.service or
          /home/roboclaw/.config/systemd/user/{{ openclaw_service_name }}.service.
          Please run 'openclaw gateway install' to create the service.
      when: >
        not openclaw_unit_file.stat.exists and
        (not user_systemd_dir is defined or
         not user_systemd_dir.stat is defined or
         not user_systemd_dir.stat.exists or
         not openclaw_user_unit_file is defined or
         not openclaw_user_unit_file.stat is defined or
         not openclaw_user_unit_file.stat.exists)

    - name: Manage openclaw system service
      ansible.builtin.systemd:
        name: "{{ openclaw_service_name }}"
        state: "{{ openclaw_state }}"
        enabled: "{{ openclaw_enabled }}"
      when: openclaw_unit_file.stat.exists

    - name: Manage openclaw user service
      ansible.builtin.systemd:
        name: "{{ openclaw_service_name }}"
        state: "{{ openclaw_state }}"
        enabled: "{{ openclaw_enabled }}"
        scope: user
      become: true
      become_user: roboclaw
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ roboclaw_uid.stdout }}"
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ roboclaw_uid.stdout }}/bus"
      when: >
        not openclaw_unit_file.stat.exists and
        openclaw_user_unit_file is defined and
        openclaw_user_unit_file.stat is defined and
        openclaw_user_unit_file.stat.exists

    # Fetch gateway token and update instance YAML file (when starting service)
    - name: Check if openclaw.json config exists
      ansible.builtin.stat:
        path: /home/roboclaw/.openclaw/openclaw.json
      register: openclaw_config_file
      when: openclaw_state == 'started'

    - name: Fetch openclaw.json from remote
      ansible.builtin.slurp:
        src: /home/roboclaw/.openclaw/openclaw.json
      register: openclaw_config_content
      when: openclaw_state == 'started' and openclaw_config_file.stat.exists
      become: true
      become_user: roboclaw

    - name: Extract gateway token from config
      ansible.builtin.set_fact:
        gateway_token: "{{ (openclaw_config_content.content | b64decode | from_json).gateway.auth.token | default('') }}"
      when: >
        openclaw_state == 'started' and
        openclaw_config_file.stat.exists and
        openclaw_config_content.content is defined

    - name: Build instance YAML path
      ansible.builtin.set_fact:
        instance_yaml_path: "../instances/{{ instance_name }}.yml"
      when: >
        openclaw_state == 'started' and
        gateway_token is defined and
        gateway_token != '' and
        instance_name != ''
      delegate_to: localhost
      become: false

    - name: Update instance YAML with gateway token
      ansible.builtin.lineinfile:
        path: "{{ instance_yaml_path }}"
        regexp: '^\s*gateway_token:'
        line: "      gateway_token: {{ gateway_token }}"
        insertafter: '^\s*software:'
        state: present
      when: >
        openclaw_state == 'started' and
        gateway_token is defined and
        gateway_token != '' and
        instance_yaml_path is defined
      delegate_to: localhost
      become: false
